#!/usr/bin/env zsh

## vars ###################################################################
cmd=$1
timestamp=$( date +%s )

## file list, realtive to ~
files=( .zshrc .zshenv )
## Github user name (probably fine as is)
ghuser=$( git config github.user )
## name of the repository on Github
repo_name='myzeshin'
## where the local copy of the repo is kept
zeshin_dir="${HOME}/src"

## make hard backups; only necessary for the truly paranoid
backup=0
backup_dir="${HOME}/.zeshin"

## end vars ###############################################################


[[ ! -d $backup_dir ]] && mkdir -p $backup_dir
[[ $backup == 1 ]] && cp -r ${HOME}/${i} $backup_dir/${i}_${timestamp}
[[ ! -d $zeshin_dir ]] && mkdir -p $zeshin_dir


case $cmd in
    init)
        cd $zeshin_dir

        curl -F login=${ghuser} -F token=$( git config github.token ) \
            https://github.com/api/v2/yaml/repos/create -F name=${repo_name}
        [[ ! -d $repo_name ]] && mkdir ${repo_name}

        cd $repo_name
        git init
        print '*~'"\n*.swp" >> .gitignore

        for i in $files; do
            print "Copying ~/$i to repo"
            cp -r ${HOME}/${i} .
            git add $i
            git commit -m "Adding $i"
        done
        git remote add origin git@github.com:${ghuser}/${repo_name}.git
        git push -u origin master
    ;;

    dl)
        cd ${zeshin_dir}/${repo_name}

        if [[ -d .git ]]; then
            git pull
        else
            git clone git@github.com:${gh_user}/${repo_name}.git
        fi

        for i in $files; do
            print "Installing $i to ~\n"
            cp -r $i ~
        done
    ;;

    ul)
        cd ${zeshin_dir}/${repo_name}
        for i in $files; do
            print "Uploading $i\n"
            cp -r ~/${i} .
            git add $i
            git commit -m "Update $i"
        done

        git push -u origin master

esac
