#!/usr/bin/env zsh


## vars #####################################################################
cmd=$1

## file list, realtive to ~
files=( .zshrc .zshenv )
## Github user name (probably fine as is)
ghuser=$( git config github.user )
## name of the repository on Github
repo_name='myzsh'
## where the local copy of the repo is kept
zeshin_dir="${HOME}/src"

## make hard backups; only necessary for the truly paranoid
backup=0
backup_dir="${HOME}/.zeshin"
[[ ! -d $backup_dir ]] && mkdir -p $backup_dir

case $cmd in
    init)
        if [[ ! -d $zeshin_dir ]]; then
            mkdir -p $zeshin_dir
        fi
        cd $zeshin_dir


        curl -F login=${ghuser} -F token=$( git config github.token ) \
            https://github.com/api/v2/yaml/repos/create -F name=${repo_name}
        [[ ! -d $repo_name ]] && mkdir ${repo_name}

        cd $repo_name
        git init
        print '*~'"\n*.swp" >> .gitignore

        for i in $files; do
            [[ $backup == 1 ]] && cp -r ${HOME}/${i} $backup_dir
            print "Copying ~/$i to repo"
            cp -r ${HOME}/${i} .
            git add $i
            git commit -m "Adding $i"
        done

        git remote add origin git@github.com:${ghuser}/${repo}.git
        git push -u origin master
        ;;

    dl)
        cd ${zeshin_dir}/${repo_name}
        git pull

        for i in $files; do
            [[ $backup == 1 ]] && cp -r ${HOME}/${i} $backup_dir
            print "Installing $i to ~\n"
            cp -r $i ~
        done
    ;;

